# Generated by Django 4.1.9 on 2023-06-22 16:53

import cms.models.base
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHistoryMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница "История развития ИИ"',
            },
            bases=(cms.models.base.MainPagePropertiesMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BigDataMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница "Большие данные"',
            },
            bases=(cms.models.base.MainPagePropertiesMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ComputerVisionMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница "Компьютерное зрение"',
            },
            bases=(cms.models.base.MainPagePropertiesMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MachineLearningMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница "Машинное обучение"',
            },
            bases=(cms.models.base.MainPagePropertiesMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=(cms.models.base.MainPagePropertiesMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MainTestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница "Тесты"',
            },
            bases=(cms.models.base.MainPagePropertiesMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата')), ('answers', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='Варианты ответов'), label='Варианты ответа'))], use_json_field=True, verbose_name='Контент')),
                ('correct_answer', models.CharField(max_length=128, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Тест',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
                ('preview_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Статья',
            },
            bases=('wagtailcore.page',),
        ),
    ]
